version: "3.1"

services:
  mysql:
    image: mysql:5.7.4
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

