// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateOrderReq struct {
	UserId int64       `json:"userId"`
	Items  []OrderItem `json:"items"`
}

type CreateOrderResp struct {
	OrderId int64 `json:"orderId"`
}

type GetOrderReq struct {
	OrderId int64 `path:"orderId"`
}

type GetOrderResp struct {
	OrderId int64       `json:"orderId"`
	UserId  int64       `json:"userId"`
	Items   []OrderItem `json:"items"`
	Status  string      `json:"status"`
}

type OrderItem struct {
	ProductId int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}
