version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: userdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etcd:
    image: quay.io/coreos/etcd:v3.4.0
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"

#  service-a:
#    build:
#      context: .
#      dockerfile: service_a/Dockerfile.serviceA
#    depends_on:
#      - etcd
#      - service-b
#    ports:
#      - "50051:50051"
#
#  service-b:
#    build:
#      context: .
#      dockerfile: service_b/Dockerfile.serviceB
#    depends_on:
#      - postgres
#      - etcd
#    ports:
#      - "50052:50052"