version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:15432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  service_a:
    build:
      context: ./ServiceA
    depends_on:
      - service_b

  service_b:
    build:
      context: ./ServiceB
    ports:
      - "50052:50052"
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    depends_on:
      - service_b
      - service_a