// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: book.proto

package server

import (
	"context"

	"bookservice/internal/logic"
	"bookservice/internal/svc"
	"bookservice/pb/book"
)

type BookServer struct {
	svcCtx *svc.ServiceContext
	book.UnimplementedBookServer
}

func NewBookServer(svcCtx *svc.ServiceContext) *BookServer {
	return &BookServer{
		svcCtx: svcCtx,
	}
}

func (s *BookServer) Add(ctx context.Context, in *book.AddRequest) (*book.AddResponse, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *BookServer) List(ctx context.Context, in *book.ListRequest) (*book.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *BookServer) Get(ctx context.Context, in *book.GetRequest) (*book.GetResponse, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *BookServer) Edit(ctx context.Context, in *book.EditRequest) (*book.EditResponse, error) {
	l := logic.NewEditLogic(ctx, s.svcCtx)
	return l.Edit(in)
}

func (s *BookServer) Delete(ctx context.Context, in *book.DeleteRequest) (*book.DeleteResponse, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
