// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: greet.proto

package server

import (
	"context"

	"tt/hello-grpc/greet/internal/logic"
	"tt/hello-grpc/greet/internal/svc"
	"tt/hello-grpc/greet/types/greet"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	greet.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) SayHello(ctx context.Context, in *greet.HelloRequest) (*greet.HelloResponse, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
